### ISSUE TITLE
Gafe is G Suite

### ISSUE THREAD

**Issue by kyyberi** [mpassid/MPASSid-connect#3]
In the demo environment login we should change "GAFE" to "G Suite". 

![screenshot-2018-5-3 mpass login - velmu](https://user-images.githubusercontent.com/1927158/39561204-eb7450c4-4eac-11e8-8199-c6296e5771d0.png)

**Comment by laze76** [comment]
Changed GAFE to G Suite in API.

**Comment by kyyberi** [comment]
Confirmed
